name: HeavenQuest
main: fr.hc.quest.HeavenQuest
depend: [HeavenCore,Citizens]
version: 0.1
commands:
  bobby:
    description: Appelle Bobby, ton meilleur ami
  scrolls:
    description: Permet la génération de parchemins
  test:
