name: HeavenCrea
version: 1.0
main: fr.heavencraft.heavencrea.HeavenCrea
depend: [HeavenCore, HeavenGuard]
load: STARTUP
commands:
  # from core
  accepter:
  rejoindre:
  spawn:
  tp:
  tphere:
  tppos:
  
  # hps
  hps:
  
  # plots
  parcelle:
  plot:
  
  # users
  jetons:
  jeton:
  money:
  
  # users.homes
  buyhome:
  home:
  sethome:
  tphome:
