name: HeavenFun
main: fr.heavencraft.heavenfun.BukkitHeavenFun
depend: [HeavenCore]
version: 1.1
commands:
#
# HeavenCore
#
  creacheat:
  endercheat:
  inventory:
  roucoups:
  tp:
  tphere:
    aliases: s
  tppos:
  tpworld:
#
# HeavenFun
#
  spawn:
  event:
  fp:
  fpa: